### ISSUE TITLE
Fatal error: Call to undefined method  /  gzcontrol.php on line 64

### ISSUE THREAD

**Issue by daftdaft** [dgrammatiko/Joomla.gzip.control#1]
I installed this on one site and it worked great, then I went to install it on a second website hosted on a different server and got the error

Fatal error: Call to undefined method JSite::get() in /plugins/system/gzcontrol/gzcontrol.php on line 64

the website is  www.centralvalleytv.net .. I've disabled the plugin to get the site working again but would like to use it somehow, any help would be appreciated

**Comment by dgrammatiko** [comment]
Is this a Joomla 2.5 site?
This plugin is for Joomla 3.x
You can easily change the line 64 from $app->get('gzip’) to $app->getCfg('gzip’) for compatibility

I hope this helps
