### ISSUE TITLE
Doens`t work with Joomla 3.4.1 for me

### ISSUE THREAD

**Issue by Diarmiud** [dgrammatiko/Joomla.gzip.control#3]
Hi,

I installed gzip on several joomla site, but it doesn't work really. For example see: http://www.bauen-und-heimwerken.de/. And yes, it's on the first position of the system plugins. Maybe it's because of a conflict with other extensions? Do you have a hint for me?

Best regards
Peter

**Comment by dgrammatiko** [comment]
@Diarmiud Sorry for the very late response, somehow I’ve never received a notification for this one.

Most probably you have enabled System Plugin Page Cache. This plugin (and many others) will not work with this plugin enabled. For further informations please read the explanation [here](https://github.com/dgt41/Joomla.gzip.control/issues/2#issuecomment-76052576)

Best regards
Dimitris
